version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cytology_backend
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: lbc_db
      OLLAMA_URL: http://ollama:11434
      CNN_MODEL_PATH: /app/models/16_0_0001_50_1110.pth
      UNET_MODEL_PATH: /app/models/unet_cell_nucleus_batch16_1_11.pth
      YOLO_MODEL_PATH: /app/models/yolo.pt
      ML_MODEL_PATH: /app/models/best_model_RandomForest_311.pkl
      ATTENTION_MODEL: /app/models/best_attention_mil_model.pth
      PORT: 8000 
    depends_on:
      - mongo
      - ollama
    volumes:
      - ./models:/app/models
      - ./data_csv:/app/data

  ollama:
    image: ollama/ollama 
    container_name: cytology_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      
    

  mongo:
    image: mongo:6.0
    container_name: cytology_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"


  frontend:
    build:
      context: ./app/web-app
      dockerfile: Dockerfile 
    container_name: cytology_frontend_dev
    ports:
      - "5173:5173" 
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8000
    volumes:
      - ./app/web-app:/app
      - /app/node_modules

volumes:
  mongo_data:
  ollama_data: